name: Master workflow

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  services:
    # Label used to access the service container
    postgres:
      # Docker Hub image
      image: postgres
      # Provide the password for postgres
      env:
        POSTGRES_HOST: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_PORT: 5432
        POSTGRES_DB: test
      # Set health checks to wait until postgres has started
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup project
      run: make setup

    - name: Check lint
      run: make lint

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: make test