on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

name: Master workflow

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.3

    services:
      postgres:
        image: postgres:12.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1

    - name: PHP Security Checker
      uses: StephaneBour/actions-php-security-checker@1.0

    - name: Setup project
      run: 	|
        composer install
        cp -n .env.example .env || true
        php artisan key:gen --ansi
        php artisan migrate
        npm install

    - name: Check lint
      run: composer run-script phpcs -- --standard=PSR12 tests

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: php artisan test